name: backwave
services:
- name: backend
  github:
    repo: codevalley/backwave
    branch: main
    deploy_on_push: true
  source_dir: /
  environment_slug: python
  build_command: pip install -r requirements.txt
  run_command: gunicorn --bind 0.0.0.0:$PORT app:app
  http_port: 5001
  envs:
  - key: MONGO_URI
    value: ${MONGO_URI}
  - key: PORT
    value: ${backend.PORT}
- name: frontend
  github:
    repo: codevalley/backwave
    branch: main
    deploy_on_push: true
  source_dir: webapp
  environment_slug: node-js
  build_command: npm install && npm run build
  run_command: npx serve -s dist
  envs:
  - key: VUE_APP_API_URL
    value: ${backend.INTERNAL_URL}