alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: backwave-api
    match:
      path:
        prefix: /api
  - component:
      name: backwave-web
    match:
      path:
        prefix: /
name: backwave-app
region: blr
services:
- build_command: pip install -r requirements.txt
  environment_slug: python
  envs:
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "5001"
  - key: MONGO_URI
    scope: RUN_AND_BUILD_TIME
    value: mongodb+srv://doadmin:st7039T142lw6Lfo@private-db-mongo-backwave-26782c0f.mongo.ondigitalocean.com/admin?authSource=admin&tls=true
  github:
    branch: main
    deploy_on_push: true
    repo: codevalley/percept
  http_port: 5001
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  name: backwave-api
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  source_dir: /
static_sites:
- build_command: npm install && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: codevalley/percept
  name: backwave-web
  output_dir: dist
  source_dir: webapp
