<template>
  <div class="font-['IBM_Plex_Sans'] min-h-screen bg-white relative">
    <div class="max-w-[859px] mx-auto px-4 sm:px-6 pb-24 sm:pb-0">
      <!-- Header Section -->
      <div class="flex flex-col sm:flex-row items-center sm:items-start mb-4 sm:mb-6">
        <div class="w-20 h-20 sm:w-14 sm:h-14 bg-secondary rounded-full mb-4 sm:mb-0 sm:mr-5 flex-shrink-0 sm:self-center"></div>
        <div class="flex-grow text-center sm:text-left">
          <h1 class="text-neutral-600 text-xl sm:text-2xl font-semibold leading-8 sm:leading-10 mb-2 sm:mb-1">{{ surveyTitle }}</h1>
          <p class="text-neutral-600 text-base sm:text-lg font-normal leading-6 sm:leading-7">{{ surveyDescription }}</p>
        </div>
      </div>

      <template v-if="!isPublished">
        <!-- Question Creation Section -->
        <div class="bg-neutral-100 rounded-[25px] p-4 sm:p-7 mb-8 sm:mb-12 relative">
          <div class="relative flex items-start mb-6">
            <inline-svg src="assets/question-icon.svg" class="text-primary mr-2 mt-1 hidden sm:block" />
            <div class="relative w-full">
              <textarea v-model="newQuestion.text" @keyup.enter="handleAddOrSuggest" @input="handleQuestionChange"
                @focus="inputFocused = true" @blur="inputFocused = false"
                class="w-full bg-transparent text-xl sm:text-[28px] font-regular text-primary focus:outline-none pr-10 transition-all duration-300 ease-in-out transform hover:scale-102 focus:scale-102 resize-none"
                :placeholder="placeholderText"
                :disabled="isSubmitted"
                rows="2">
              </textarea>
              <inline-svg v-if="newQuestion.isAutogenerated" src="assets/magic-icon.svg"
                class="absolute right-2 top-2 w-6 h-6 text-neutral-300" />
            </div>
          </div>
          <div class="flex flex-col sm:flex-row justify-between items-stretch sm:items-center space-y-4 sm:space-y-0">
            <div class="flex space-x-4 sm:space-x-5">
              <button @click="setQuestionType('scale')" :class="['flex-1 sm:w-28 h-10 rounded-full flex items-center justify-center space-x-2 border border-neutral-300',
                newQuestion.response_type === 'scale' ? 'bg-primary text-white' : 'bg-white text-primary']"
                :disabled="isSubmitted">
                <inline-svg src="assets/scale-icon.svg"
                  :class="newQuestion.response_type === 'scale' ? 'text-white' : 'text-primary'" class="w-6 h-6"
                  :key="newQuestion.response_type === 'scale' ? 'scale' : 'default'" />
                <span class="text-base font-medium">Rating</span>
              </button>
              <button @click="setQuestionType('boolean')" :class="['flex-1 sm:w-28 h-10 rounded-full flex items-center justify-center space-x-2 border border-neutral-300',
                newQuestion.response_type === 'boolean' ? 'bg-primary text-white' : 'bg-white text-primary']"
                :disabled="isSubmitted">
                <inline-svg src="assets/yes-no-icon.svg"
                  :class="newQuestion.response_type === 'boolean' ? 'text-white' : 'text-primary'" class="w-6 h-6"
                  :key="newQuestion.response_type === 'boolean' ? 'boolean' : 'default'" />
                <span class="text-base font-medium">Yes/No</span>
              </button>
            </div>
            <div class="flex items-center space-x-2 justify-end sm:justify-start">
              <transition name="fade-scale" mode="out-in">
                <button v-if="newQuestion.text.trim() && !newQuestion.isAutogenerated" 
                        key="magic-button" 
                        @click="suggestReplacementQuestion"
                        class="w-14 sm:w-10 h-10 rounded-full flex items-center justify-center bg-accent" 
                        :disabled="isSubmitted"
                        v-tooltip="'Want some question suggestions?'">
                  <inline-svg src="assets/magic-icon.svg" class="w-5 h-5 text-white" />
                </button>
              </transition>
              <transition name="fade-scale" mode="out-in">
                <button @click="handleAddOrSuggest" :disabled="isSubmitted"
                  :key="newQuestion.text.trim() ? 'add' : 'suggest'" :class="[
                    'flex-1 sm:w-32 h-10 rounded-full flex items-center justify-center space-x-2 border',
                    newQuestion.text.trim() && !isSubmitted
                      ? 'bg-accent-green text-primary border-accent-green'
                      : isSubmitted
                        ? 'bg-gray-200 text-neutral-300 border-neutral-100'
                        : 'bg-accent text-white border-accent'
                  ]">
                  <inline-svg :src="newQuestion.text.trim() ? 'assets/yes-icon.svg' : 'assets/magic-icon.svg'"
                    class="w-5 h-5 mr-1" :class="newQuestion.text.trim() ? 'text-primary' : 'text-white'" />
                  <span class="text-base font-medium">{{ newQuestion.text.trim() ? 'Add' : 'Suggest' }}</span>
                </button>
              </transition>
            </div>
          </div>
        </div>
        
        <!-- Question List Section -->
        <div v-if="questions.length > 0" class="bg-neutral-100 rounded-[25px] p-4 sm:p-7 mb-8 sm:mb-12">
          <transition-group name="list" tag="div" class="space-y-6">
            <div v-for="(question, index) in questions" :key="question.id" 
                 class="flex flex-col sm:flex-row sm:items-center sm:justify-between p-4 sm:p-0 bg-white sm:bg-transparent rounded-2xl sm:rounded-none shadow-sm sm:shadow-none">
              <div class="flex items-center mb-4 sm:mb-0">
                <button @click="editQuestion(index)" class="text-accent hover:text-accent-dark focus:outline-none mr-2 sm:ml-0">
                  <inline-svg src="assets/edit-icon.svg" class="w-5 h-5" />
                </button>
                <inline-svg
                  :src="question.response_type === 'scale' ? 'assets/scale-icon.svg' : 'assets/yes-no-icon.svg'"
                  :class="[
                    creatorAnswers[index] !== null ? 'text-primary' : 'text-neutral-400 sm:text-primary', 
                    'w-6 h-6 sm:w-8 sm:h-8 flex-shrink-0 mr-2 sm:mr-4'
                  ]"
                />
                <span class="text-lg sm:text-2xl sm:mr-2 break-words"
                      :class="creatorAnswers[index] !== null ? 'text-primary' : 'text-neutral-400 sm:text-primary'">
                  {{ question.text }}
                </span>
                <inline-svg v-if="question.isAutogenerated" src="assets/magic-icon.svg" class="w-5 h-5 text-accent ml-2" />
              </div>
              <div class="flex justify-center sm:justify-end items-center space-x-2 sm:space-x-3">
                <div v-if="question.response_type === 'scale'" class="flex space-x-2 sm:space-x-3"
                    v-tooltip="index === 0 ? 'Add a self-assessment first to baseline the answers' : ''">
                  <button v-for="n in 5" :key="n" @click="selectAnswer(index, n)" 
                          :class="['w-8 h-8 sm:w-[30px] sm:h-[30px] rounded-full border flex items-center justify-center transition-colors duration-200 ease-in-out',
                            n <= creatorAnswers[index] ? 'bg-primary border-primary' : 'bg-white border-neutral-300']"
                          :disabled="isSubmitted">
                    <div :class="['w-4 h-4 sm:w-[18px] sm:h-[18px] rounded-full', n <= creatorAnswers[index] ? 'bg-white' : 'bg-transparent']"></div>
                  </button>
                </div>
                <div v-else class="flex space-x-2 sm:space-x-3"
                    v-tooltip="index === 0 ? 'Add a self-assessment first to baseline the answers' : ''">
                  <button @click="selectAnswer(index, true)"
                          :class="['w-8 h-8 sm:w-[30px] sm:h-[30px] rounded-full border flex items-center justify-center transition-colors duration-200 ease-in-out',
                            creatorAnswers[index] === true ? 'bg-primary border-primary' : 'bg-white border-neutral-300']" 
                          :disabled="isSubmitted">
                    <inline-svg src="assets/yes-icon.svg" :class="['w-4 h-4', creatorAnswers[index] === true ? 'text-white' : 'text-neutral-300']" />
                  </button>
                  <button @click="selectAnswer(index, false)"
                          :class="['w-8 h-8 sm:w-[30px] sm:h-[30px] rounded-full border flex items-center justify-center transition-colors duration-200 ease-in-out',
                            creatorAnswers[index] === false ? 'bg-primary border-primary' : 'bg-white border-neutral-300']" 
                          :disabled="isSubmitted">
                    <inline-svg src="assets/no-icon.svg" :class="['w-4 h-4', creatorAnswers[index] === false ? 'text-white' : 'text-neutral-300']" />
                  </button>
                </div>
              </div>
            </div>
          </transition-group>
        </div>

        <!-- Publish Section -->
        <div class="relative">
          <!-- Desktop layout -->
          <div class="hidden sm:block bg-accent-green rounded-[999px] p-4 mb-4">
            <div class="flex items-center justify-between">
              <div class="flex items-center space-x-6">
                <FancyInput
                  v-model="surveyCode"
                  :icon="'/assets/bookmark-icon.svg'"
                  :placeholder="'survey ID'"
                  :is-checking="isCheckingCode('survey')"
                  :is-valid="isCodeValid('survey')"
                  :is-error="isCodeInvalid('survey')"
                  :max-width="'300px'"
                  :border-width="2"
                  input-height="40px"
                  icon-size="24px"
                  font-size="text-sm"
                  @rotate="rotateCode('survey')"
                  @input="handleCodeInput('survey')"
                  :loader-color="'#BE185D'"
                  :valid-border-color="'#22C55E'"  
                  :bg-color="'white'"  
                  :text-color="'text-neutral-500'"
                  :error-bg-color="'#EF4444'"
                  :icon-color="'text-neutral-500'"
                  :min-width="'100px'"
                  v-tooltip="'A Shareable shortcode for the review'"
                />
                <FancyInput
                  v-model="userCode"
                  :icon="'/assets/user-icon.svg'"
                  :placeholder="'user name'"
                  :is-checking="isCheckingCode('user')"
                  :is-valid="isCodeValid('user')"
                  :is-error="isCodeInvalid('user')"
                  :border-width="2"
                  input-height="40px"
                  icon-size="24px"
                  font-size="text-sm"
                  @rotate="rotateCode('user')"
                  @input="handleCodeInput('user')"
                  :loader-color="'#BE185D'"
                  :valid-border-color="'#22C55E'"  
                  :bg-color="'white'"  
                  :text-color="'text-neutral-500'"
                  :error-bg-color="'#EF4444'"
                  :icon-color="'text-neutral-500'"
                  :min-width="'100px'"
                  v-tooltip="'A secret usercode for you to see results later'"
                />
              </div>
              <FancyButton
                label="Publish"
                :disabled="!canPublish"
                :is-actioning="isPublishing"
                @click="finishSurvey"
                :border-width="3"
                button-height="48px"
                icon-size="24px"
                font-size="text-xl"
                :min-width="'128px'"
                bg-color="black"
                border-color="black"
                disabled-bg-color="gray"
                disabled-border-color="gray"
                text-color="text-white"
                disabled-text-color="text-gray-400"
              />
            </div>
          </div>

          <!-- Mobile layout -->
          <div class="sm:hidden bg-accent-green rounded-[25px] p-4 mb-4">
            <div class="space-y-4">
              <div>
                <FancyInput
                  v-model="surveyCode"
                  :icon="'/assets/bookmark-icon.svg'"
                  :placeholder="'survey ID'"
                  :is-checking="isCheckingCode('survey')"
                  :is-valid="isCodeValid('survey')"
                  :is-error="isCodeInvalid('survey')"
                  :border-width="2"
                  input-height="40px"
                  icon-size="24px"
                  font-size="text-sm"
                  @rotate="rotateCode('survey')"
                  @input="handleCodeInput('survey')"
                  :loader-color="'#BE185D'"
                  :valid-border-color="'#22C55E'"  
                  :bg-color="'white'"  
                  :text-color="'text-neutral-500'"
                  :error-bg-color="'#EF4444'"
                  :icon-color="'text-neutral-500'"
                  class="w-full"
                  :min-width="'100%'"
                />
                <p class="text-xs text-primary mt-1 ml-2">A Shareable shortcode for the review</p>
              </div>
              <div>
                <FancyInput
                  v-model="userCode"
                  :icon="'/assets/user-icon.svg'"
                  :placeholder="'user name'"
                  :is-checking="isCheckingCode('user')"
                  :is-valid="isCodeValid('user')"
                  :is-error="isCodeInvalid('user')"
                  :border-width="2"
                  input-height="40px"
                  icon-size="24px"
                  font-size="text-sm"
                  @rotate="rotateCode('user')"
                  @input="handleCodeInput('user')"
                  :loader-color="'#BE185D'"
                  :valid-border-color="'#22C55E'"  
                  :bg-color="'white'"  
                  :text-color="'text-neutral-500'"
                  :error-bg-color="'#EF4444'"
                  :icon-color="'text-neutral-500'"
                  class="w-full"
                  :min-width="'100%'"
                />
                <p class="text-xs text-primary mt-1 ml-2">A secret usercode for you to see results later</p>
              </div>
            </div>
          </div>

          <!-- Error Notes Section -->
          <div class="mb-6">
            <div v-if="!allQuestionsAnswered || isCodeInvalid('survey') || isCodeInvalid('user')" class="flex flex-col space-y-2 text-accent">
              <div v-if="!allQuestionsAnswered" class="flex items-center space-x-2">
                <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
                <span class="text-sm font-medium">Complete self review before publishing</span>
              </div>
              <div v-if="isCodeInvalid('survey')" class="flex items-center space-x-2">
                <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
                <span class="text-sm font-medium">
                  {{ getCodeErrorMessage('survey') }}
                </span>
              </div>
              <div v-if="isCodeInvalid('user')" class="flex items-center space-x-2">
                <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
                <span class="text-sm font-medium">
                  {{ getCodeErrorMessage('user') }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </template>

      <!-- Published Section -->
      <div v-if="isPublished" class="bg-accent-green rounded-[25px] p-4 sm:p-7 mb-12">
        <!-- Hide header on mobile -->
        <div class="hidden sm:block w-full text-primary text-2xl font-bold font-['IBM Plex Sans'] leading-9 mb-6 text-left">
          The post is published and live!
        </div>

        <div class="flex flex-col space-y-6 sm:space-y-8">
          <div class="flex flex-col space-y-1">
            <div class="flex flex-col sm:flex-row sm:items-center space-y-2 sm:space-y-0 sm:space-x-4">
              <span class="text-primary text-base sm:text-lg font-normal leading-7">Review link</span>
              <button
                @click="openAndCopy('survey')"
                class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary w-full sm:w-auto"
              >
                <span class="text-base font-medium truncate mr-2">{{ surveyCode }}</span>
                <inline-svg 
                  @click.stop="copyToClipboard('surveyCode')" 
                  src="assets/copy-icon.svg"
                  class="w-5 h-5 flex-shrink-0"
                />
              </button>
            </div>
            <span class="text-primary text-sm italic sm:ml-4">Share it with your friends for feedback</span>
          </div>

          <div class="flex flex-col space-y-1">
            <div class="flex flex-col sm:flex-row sm:items-center space-y-2 sm:space-y-0 sm:space-x-4">
              <span class="text-primary text-base sm:text-lg font-normal leading-7">Result link</span>
              <button
                @click="openAndCopy('user')"
                class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary w-full sm:w-auto"
              >
                <span class="text-base font-medium truncate mr-2">{{ userCode }}</span>
                <inline-svg 
                  @click.stop="copyToClipboard('userCode')" 
                  src="assets/copy-icon.svg" 
                  class="w-5 h-5 flex-shrink-0" 
                />
              </button>
            </div>
            <span class="text-primary text-sm italic sm:ml-4">Bookmark and come here later to see results</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile Publish Button - Moved outside the main content div -->
    <div class="sm:hidden fixed bottom-0 left-0 right-0 p-4 bg-white border-t border-gray-200 z-50">
      <FancyButton
        label="Publish"
        :disabled="!canPublish"
        :is-actioning="isPublishing"
        @click="finishSurvey"
        :border-width="3"
        button-height="48px"
        icon-size="24px"
        font-size="text-xl"
        bg-color="black"
        border-color="black"
        disabled-bg-color="gray"
        disabled-border-color="gray"
        text-color="text-white"
        disabled-text-color="text-gray-400"
        :full-width="true"
      />
    </div>

    <ToastView :message="toastMessage" :type="toastType" @hidden="clearToast" />
  </div>
</template>

<script>
import { ref, computed, watch, onMounted, reactive } from 'vue';
import { useI18n } from 'vue-i18n';
import api from '@/services/api';
import confetti from 'canvas-confetti';
import InlineSvg from 'vue-inline-svg';
import ToastView from '@/components/ToastView.vue';
import FancyInput from '@/components/FancyInput.vue';
import FancyButton from '@/components/FancyButton.vue';
import debounce from 'lodash/debounce';

export default {
  name: 'CreateView',
  components: {
    InlineSvg,
    ToastView,
    FancyInput,
    FancyButton,
  },
  setup() {
    const { t } = useI18n();
    const surveyTitle = ref(t('createView.title'));
    const surveyDescription = ref(t('createView.description'));
    const newQuestion = ref({ text: '', response_type: 'scale', isAutogenerated: false });
    const questions = ref([]);
    const creatorAnswers = ref([]);
    const isLoading = ref(false);
    const isSubmitted = ref(false);
    const isPublished = ref(false);
    const errorMessage = ref('');
    const showSuccess = ref(false);
    const surveyCode = ref('');
    const inputFocused = ref(false);
    const toastMessage = ref('');
    const toastType = ref('');
    const userCode = ref('');
    const surveyLink = ref('');
    const resultsLink = ref('');
    const availableCodes = ref({ survey: [], user: [] });
    const codeStatus = ref({ survey: null, user: null });
    const isChecking = reactive({ survey: false, user: false });
    const isPublishing = ref(false);
    const baseUrl = computed(() => process.env.VUE_APP_BASE_URL || '');
    const showUserCodeTooltip = ref(false);
    const showSurveyCodeTooltip = ref(false);
    const editingQuestionIndex = ref(null);

    function editQuestion(index) {
      const questionToEdit = questions.value[index];
      newQuestion.value = { ...questionToEdit };
      editingQuestionIndex.value = index;
      questions.value.splice(index, 1);
      creatorAnswers.value.splice(index, 1);
    }

    console.log("Base URL: ", process.env.VUE_APP_BASE_URL);
    console.log("VUE API URL", process.env.VUE_APP_API_URL);
    const placeholderText = ref('Enter your question here');
    const placeholders = [
      'Enter your question here',
      'How would you rate...?',
      'Do you think...?',
      'What\'s your opinion on...?'
    ];
    let placeholderIndex = 0;
    
    const animatePlaceholder = () => {
      setInterval(() => {
        placeholderIndex = (placeholderIndex + 1) % placeholders.length;
        placeholderText.value = placeholders[placeholderIndex];
      }, 3000); // Change every 3 seconds
    };

    const isCheckingCode = (type) => {
      return isChecking[type];
    };
    
    const isValidFormat = (code) => {
      const validFormat = /^[a-zA-Z0-9-]+$/;
      return typeof code === 'string' && code.length >= 5 && validFormat.test(code);
    };

    const handleCodeInput = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      const otherCode = type === 'survey' ? userCode.value : surveyCode.value;
      if (isValidFormat(code)) {
        if (code === otherCode) {
          codeStatus.value[type] = 'invalid';
          isChecking[type] = false;
        } else {
          codeStatus.value[type] = null;
          isChecking[type] = true;
          debounceCheckCode(type);
        }
      } else {
        codeStatus.value[type] = 'invalid';
        isChecking[type] = false;
      }
    };

    const debounceCheckCode = debounce((type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      if (isValidFormat(code)) {
        checkCodeAvailability(type);
      } else {
        isChecking[type] = false;
      }
    }, 750);

    const getCodeErrorMessage = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      const otherCode = type === 'survey' ? userCode.value : surveyCode.value;
      if (!code || code.length < 5) {
        return `${type === 'survey' ? 'Survey' : 'User'} code must be at least 5 characters long.`;
      }
      if (!/^[a-zA-Z0-9-]+$/.test(code)) {
        return `${type === 'survey' ? 'Survey' : 'User'} code can only contain letters, numbers, and hyphens.`;
      }
      if (code === otherCode) {
        return `${type === 'survey' ? 'Survey' : 'User'} code cannot be the same as the ${type === 'survey' ? 'user' : 'survey'} code.`;
      }
      return `Invalid ${type === 'survey' ? 'survey' : 'user'} code. Please choose a different one.`;
    };

    const canPublish = computed(() => 
      allQuestionsAnswered.value && 
      isCodeValid('survey') && 
      isCodeValid('user') && 
      !isLoading.value && 
      !isSubmitted.value
    );

    const isCodeValid = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      const otherCode = type === 'survey' ? userCode.value : surveyCode.value;
      return !isChecking[type] && isValidFormat(code) && codeStatus.value[type] === 'valid' && code !== otherCode;
    };

    const isCodeInvalid = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      const otherCode = type === 'survey' ? userCode.value : surveyCode.value;
      return !isChecking[type] && (!isValidFormat(code) || codeStatus.value[type] === 'invalid' || code === otherCode);
    };

    const allQuestionsAnswered = computed(() =>
      questions.value.length > 0 &&
      creatorAnswers.value.length === questions.value.length &&
      creatorAnswers.value.every(answer => answer !== null && answer !== undefined)
    );

    const suggestedQuestions = [
      { text: "How well do I communicate my ideas?", response_type: "scale" },
      { text: "Am I open to feedback from others?", response_type: "boolean" },
      { text: "How effectively do I manage my time?", response_type: "scale" },
      { text: "Do I actively listen to you and other colleagues?", response_type: "boolean" },
      { text: "How well do I handle stress and pressure?", response_type: "scale" },
      { text: "Am I proactive in solving problems?", response_type: "boolean" },
      { text: "How would I rate my leadership skills?", response_type: "scale" },
      { text: "Do I consistently meet deadlines?", response_type: "boolean" },
      { text: "How adaptable am I to change?", response_type: "scale" },
      { text: "Do I take responsibility for my mistakes?", response_type: "boolean" }
    ];

    async function fetchInitialCodes() {
      console.log('Starting fetchInitialCodes');

      
      isChecking.survey = true;
      isChecking.user = true;
      try {
        const response = await api.getIds(10);
        availableCodes.value.survey = response.data.ids.slice(0, 5);
        availableCodes.value.user = response.data.ids.slice(5);
        surveyCode.value = availableCodes.value.survey[0];
        userCode.value = availableCodes.value.user[0];

        
        // Validate the codes
        await Promise.all([
          checkCodeAvailability('survey'),
          checkCodeAvailability('user')
        ]);
      } catch (error) {
        console.error('Error fetching initial codes:', error);
        toastMessage.value = t('createView.errorFetchingCodes');
        toastType.value = 'error';
        codeStatus.value.survey = 'invalid';
        codeStatus.value.user = 'invalid';
      } finally {
        // Add a small delay before setting isChecking to false
        setTimeout(() => {
          isChecking.survey = false;
          isChecking.user = false;
          console.log('Finished fetchInitialCodes, isChecking:', isChecking);
        }, 1000); // 1 second delay
      }    
    }

    function rotateCode(type) {
      const codes = availableCodes.value[type];
      const currentCode = type === 'survey' ? surveyCode.value : userCode.value;
      const currentIndex = codes.indexOf(currentCode);
      const nextIndex = (currentIndex + 1) % codes.length;
      if (type === 'survey') {
        surveyCode.value = codes[nextIndex];
      } else {
        userCode.value = codes[nextIndex];
      }
      codeStatus.value[type] = 'valid';
    }

    async function checkCodeAvailability(type) {
      const code = type === 'survey' ? surveyCode.value : userCode.value;

      isChecking[type] = true;
      codeStatus.value[type] = null;

      try {
        const response = await api.checkIdAvailability(code);

        // Ensure the animation runs for at least 1 second
        await new Promise(resolve => setTimeout(resolve, 1000));

        if (!response.data || typeof response.data.available !== 'boolean') {
          throw new Error('Unexpected API response format');
        }

        if (response.data.available) {
          codeStatus.value[type] = 'valid';
          if (type === 'survey') {
            availableCodes.value.survey[0] = surveyCode.value;
          } else {
            availableCodes.value.user[0] = userCode.value;
          }
        } else {
          codeStatus.value[type] = 'invalid';
          console.log(`${type} code ${code} is not available`);
          toastMessage.value = t('createView.codeNotAvailable');
          toastType.value = 'error';
        }
      } catch (error) {
        console.error(`Error checking ${type} code availability:`, error);
        codeStatus.value[type] = 'invalid';
        toastMessage.value = t('createView.errorCheckingCode');
        toastType.value = 'error';
      } finally {
        isChecking[type] = false;
      }
    }

    function setQuestionType(type) {
      newQuestion.value.response_type = type;
      newQuestion.value.isAutogenerated = false;
    }

    function handleAddOrSuggest() {
      if (newQuestion.value.text.trim()) {
        addQuestion();
      } else {
        suggestQuestion();
      }
    }

    function addQuestion() {
      if (newQuestion.value.text.trim() && !isSubmitted.value) {
        if (editingQuestionIndex.value !== null) {
          // Update existing question
          questions.value.splice(editingQuestionIndex.value, 0, {
            ...newQuestion.value,
            id: Date.now() // Assign a new ID to trigger re-render
          });
          creatorAnswers.value.splice(editingQuestionIndex.value, 0, null);
          editingQuestionIndex.value = null;
        } else {
          // Add new question
          questions.value.push({
            id: Date.now(),
            ...newQuestion.value
          });
          creatorAnswers.value.push(null);
        }
        newQuestion.value = { text: '', response_type: 'scale', isAutogenerated: false };
        checkEasterEgg();
      }
    }

    function suggestQuestion() {
      const randomIndex = Math.floor(Math.random() * suggestedQuestions.length);
      const suggestedQuestion = suggestedQuestions[randomIndex];

      newQuestion.value = {
        text: suggestedQuestion.text,
        response_type: suggestedQuestion.response_type,
        isAutogenerated: true
      };
    }

    function handleQuestionChange() {
      if (newQuestion.value.isAutogenerated && newQuestion.value.text !== suggestedQuestions.find(q => q.text === newQuestion.value.text)?.text) {
        newQuestion.value.isAutogenerated = false;
      }
    }

    function suggestReplacementQuestion() {
      suggestQuestion();
    }

    function selectAnswer(index, value) {
      if (!isSubmitted.value) {
        creatorAnswers.value[index] = value;
      }
    }

    function celebrateSuccess() {
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 }
      });
    }

    function clearToast() {
      toastMessage.value = '';
      toastType.value = '';
    }

    const openAndCopy = (type) => {
      const url = type === 'survey' ? surveyLink.value : resultsLink.value;
      window.open(url, '_blank');
      copyToClipboard(type);
    };

    const copyToClipboard = (type) => {
      let textToCopy;
      if (type === 'survey') {
        textToCopy = surveyLink.value;
      } else if (type === 'user') {
        textToCopy = resultsLink.value;
      } else if (type === 'surveyCode') {
        textToCopy = surveyCode.value;
      } else if (type === 'userCode') {
        textToCopy = userCode.value;
      }

      navigator.clipboard.writeText(textToCopy).then(() => {
        toastMessage.value = t('createView.copySuccess');
        toastType.value = 'success';
      }, (err) => {
        console.error('Could not copy text: ', err);
        toastMessage.value = t('createView.copyError');
        toastType.value = 'error';
      });
    };

    // const successAnimation = () => {
    //   const successElement = document.createElement('div');
    //   successElement.textContent = '✓';
    //   successElement.style.cssText = `
    //     position: fixed;
    //     top: 50%;
    //     left: 50%;
    //     transform: translate(-50%, -50%);
    //     font-size: 48px;
    //     color: #22C55E;
    //     opacity: 0;
    //     transition: all 0.5s ease-out;
    //   `;
    //   document.body.appendChild(successElement);
      
    //   // Animate the success message
    //   setTimeout(() => {
    //     successElement.style.opacity = '1';
    //     successElement.style.transform = 'translate(-50%, -50%) scale(1.2)';
    //   }, 0);
      
    //   setTimeout(() => {
    //     successElement.style.opacity = '0';
    //     successElement.style.transform = 'translate(-50%, -50%) scale(0.8)';
    //   }, 1000);
      
    //   setTimeout(() => {
    //     document.body.removeChild(successElement);
    //   }, 1500);
    // };
    
    // Easter egg: Trigger a special animation when the user adds 5 questions quickly
    let questionAddedTimes = [];
    let lastEasterEggTrigger = 0;
    const EASTER_EGG_COOLDOWN = 30000; // 30 seconds cooldown
    const checkEasterEgg = () => {
      const now = Date.now();
      questionAddedTimes.push(now);
      
      // Keep only the last 5 timestamps
      if (questionAddedTimes.length > 5) {
        questionAddedTimes = questionAddedTimes.slice(-5);
      }
      
      // Check if 5 questions were added within 10 seconds
      if (questionAddedTimes.length === 5 && (now - questionAddedTimes[0]) < 10000) {
        // Check if enough time has passed since the last trigger
        if (now - lastEasterEggTrigger > EASTER_EGG_COOLDOWN) {
          triggerEasterEgg();
          lastEasterEggTrigger = now;
          // Reset the questionAddedTimes after triggering
          questionAddedTimes = [];
        }
      }
    };
    
    const triggerEasterEgg = () => {
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C1']
      });
    };

    async function finishSurvey() {
      if (isSubmitted.value || !allQuestionsAnswered.value) return;

      isPublishing.value = true;
      isLoading.value = true;
      errorMessage.value = '';
      try {
        const surveyData = {
          survey_id: surveyCode.value,
          user_code: userCode.value,
          title: surveyTitle.value,
          description: surveyDescription.value,
          questions: questions.value.map((q, index) => ({
            ...q,
            creator_answer: creatorAnswers.value[index]
          }))
        };

        const response = await api.createSurvey(surveyData);
        console.log('Survey created', response.data);
        surveyLink.value =  `${baseUrl.value}/participate/${surveyCode.value}`;
        resultsLink.value = `${baseUrl.value}/results/${surveyCode.value}/${userCode.value}`;
        isSubmitted.value = true;
        isPublished.value = true;
        showSuccess.value = true;
        celebrateSuccess();
        toastMessage.value = t('createView.toastSuccess');
        toastType.value = 'success';
      } catch (error) {
        console.error('Error creating survey:', error);
        errorMessage.value = t('createView.toastError');
        toastMessage.value = t('createView.toastError');
        toastType.value = 'error';
      } finally {
        isLoading.value = false;
        isPublishing.value = false;
      }
    }

    // Function to show tooltips sequentially
    const showSequentialTooltips = () => {
      if (questions.value.length === 1) {
        showUserCodeTooltip.value = true;
        setTimeout(() => {
          showUserCodeTooltip.value = false;
          setTimeout(() => {
            showSurveyCodeTooltip.value = true;
            setTimeout(() => {
              showSurveyCodeTooltip.value = false;
            }, 5000); // Hide survey code tooltip after 5 seconds
          }, 500); // Wait 0.5 seconds before showing survey code tooltip
        }, 5000); // Hide user code tooltip after 5 seconds
      }
    };

    onMounted(async () => {
      await fetchInitialCodes();
      animatePlaceholder();
    });

    watch(() => newQuestion.value.text, handleQuestionChange);

    // Watch for changes in questions array
    watch(() => questions.value.length, (newLength, oldLength) => {
      if (newLength === 1 && oldLength === 0) {
        showSequentialTooltips();
      }
    });

    return {
      t,
      surveyTitle,
      surveyDescription,
      newQuestion,
      questions,
      creatorAnswers,
      isLoading,
      isSubmitted,
      isPublished,
      errorMessage,
      showSuccess,
      surveyCode,
      surveyLink,
      allQuestionsAnswered,
      inputFocused,
      toastMessage,
      toastType,
      setQuestionType,
      suggestReplacementQuestion,
      suggestQuestion,
      addQuestion,
      handleAddOrSuggest,
      selectAnswer,
      finishSurvey,
      clearToast,
      userCode,
      resultsLink,
      rotateCode,
      checkCodeAvailability,
      openAndCopy,
      copyToClipboard,
      isCheckingCode,
      isCodeValid,
      isCodeInvalid,
      debounceCheckCode,
      canPublish,
      isValidFormat,
      handleCodeInput,
      getCodeErrorMessage,
      isPublishing,
      placeholderText,
      showUserCodeTooltip,
      showSurveyCodeTooltip,
      editQuestion,
      editingQuestionIndex,
    };
  }
}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&display=swap');

/* Animations */
@keyframes blink {
  0%, 100% { opacity: 0; }
  50% { opacity: 1; }
}

/* General styles */
.animate-blink {
  animation: blink 1s infinite;
}

/* Code input styles */
.code-input-container {
  position: relative;
}

.code-input-container .measure-span {
  visibility: hidden;
  white-space: pre;
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
}

/* Transition styles */
.fade-scale-enter-active,
.fade-scale-leave-active,
.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}

.fade-scale-enter-from,
.fade-scale-leave-to {
  opacity: 0;
  transform: scale(0.9);
}

.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}

.list-move {
  transition: transform 0.5s ease;
}

/* Tooltip styles */
.v-tooltip {
  display: block;
  z-index: 10000;
}

.v-tooltip .tooltip-inner {
  background: #1F2937;
  color: white;
  border-radius: 16px;
  padding: 5px 10px 4px;
}

.v-tooltip .tooltip-arrow {
  width: 0;
  height: 0;
  border-style: solid;
  position: absolute;
  margin: 5px;
  border-color: #1F2937;
}

.v-tooltip[x-placement^="top"] .tooltip-arrow {
  border-width: 5px 5px 0 5px;
  border-left-color: transparent !important;
  border-right-color: transparent !important;
  border-bottom-color: transparent !important;
  bottom: -5px;
  left: calc(50% - 5px);
  margin-top: 0;
  margin-bottom: 0;
}

/* Add styles for other placements if needed */

/* Micro-interactions */
.transition-all {
  transition-property: all;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
}

.duration-300 {
  transition-duration: 300ms;
}

.ease-in-out {
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}

.transform {
  transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}

.hover\:scale-102:hover {
  --tw-scale-x: 1.02;
  --tw-scale-y: 1.02;
  transform: var(--tw-transform);
}

.focus\:scale-102:focus {
  --tw-scale-x: 1.02;
  --tw-scale-y: 1.02;
  transform: var(--tw-transform);
}
.list-enter-active,
.list-leave-active {
  transition: all 0.5s ease;
}
.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}
.list-move {
  transition: transform 0.5s ease;
}
textarea {
  resize: none !important;
}
.pb-24 {
  padding-bottom: 6rem;
}
.truncate {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.fixed {
  z-index: 50;
}
</style>