<template>
  <div class="font-['IBM_Plex_Sans'] min-h-screen bg-white">
    <div class="max-w-[859px] mx-auto">
      <div class="flex items-start mb-4">
        <!-- Profile Icon -->
        <div class="w-14 h-14 bg-secondary rounded-full mr-5 flex-shrink-0 mt-2"></div>

        <!-- Header Section -->
        <div class="flex-grow">
          <h1 class="text-neutral-600 text-2xl font-semibold leading-10 text-left">{{ surveyTitle }}</h1>
          <p class="text-neutral-600 text-lg font-normal leading-7 text-left">{{ surveyDescription }}</p>
        </div>
      </div>

      <template v-if="!isPublished">
        <!-- Question Input Section -->
        <div class="bg-neutral-100 rounded-[25px] p-7 mb-12 relative">
          <div class="relative flex items-center mb-6">
            <inline-svg src="assets/question-icon.svg" class="text-primary mr-2 mt-1" />
            <div class="relative w-full">
              <input v-model="newQuestion.text" @keyup.enter="handleAddOrSuggest" @input="handleQuestionChange"
                @focus="inputFocused = true" @blur="inputFocused = false"
                class="w-full bg-transparent text-[28px] font-regular text-primary focus:outline-none pr-10"
                :placeholder="inputFocused ? '' : 'Enter your question here'" :disabled="isSubmitted">
              <inline-svg v-if="newQuestion.isAutogenerated" src="assets/magic-icon.svg"
                class="absolute right-2 top-1/2 transform -translate-y-1/2 w-6 h-6 text-neutral-300" />
            </div>
            <span v-if="!newQuestion.text && !inputFocused"
              class="absolute right-0 top-1/2 transform -translate-y-1/2 text-neutral-300 text-[34px] font-bold animate-blink">_</span>
          </div>
          <div class="flex justify-between items-center">
            <div class="flex space-x-5">
              <!-- Scale button -->
              <button @click="setQuestionType('scale')" :class="['w-28 h-10 rounded-full flex items-center justify-center space-x-2 border border-neutral-300',
                newQuestion.response_type === 'scale' ? 'bg-primary text-white' : 'bg-white text-primary']"
                :disabled="isSubmitted">
                <inline-svg src="assets/scale-icon.svg"
                  :class="newQuestion.response_type === 'scale' ? 'text-white' : 'text-primary'" class="w-6 h-6"
                  :key="newQuestion.response_type === 'scale' ? 'scale' : 'default'" />
                <span class="text-base font-medium">Rating</span>
              </button>

              <!-- Yes/No button -->
              <button @click="setQuestionType('boolean')" :class="['w-28 h-10 rounded-full flex items-center justify-center space-x-2 border border-neutral-300',
                newQuestion.response_type === 'boolean' ? 'bg-primary text-white' : 'bg-white text-primary']"
                :disabled="isSubmitted">
                <inline-svg src="assets/yes-no-icon.svg"
                  :class="newQuestion.response_type === 'boolean' ? 'text-white' : 'text-primary'" class="w-6 h-6"
                  :key="newQuestion.response_type === 'boolean' ? 'boolean' : 'default'" />
                <span class="text-base font-medium">Yes/No</span>
              </button>
            </div>

            <div class="flex items-center space-x-2">
              <transition name="fade-scale" mode="out-in">
                <button v-if="newQuestion.text.trim() && !newQuestion.isAutogenerated" key="magic-button" @click="suggestReplacementQuestion"
                  class="w-10 h-10 rounded-full flex items-center justify-center bg-accent" :disabled="isSubmitted">
                  <inline-svg src="assets/magic-icon.svg" class="w-5 h-5 text-white" />
                </button>
              </transition>

              <transition name="fade-scale" mode="out-in">
                <button @click="handleAddOrSuggest" :disabled="isSubmitted"
                  :key="newQuestion.text.trim() ? 'add' : 'suggest'" :class="[
                    'w-32 h-10 rounded-full flex items-center justify-center space-x-2 border',
                    newQuestion.text.trim() && !isSubmitted
                      ? 'bg-accent-green text-primary border-accent-green'
                      : isSubmitted
                        ? 'bg-gray-200 text-neutral-300 border-neutral-100'
                        : 'bg-accent text-white border-accent'
                  ]">
                  <inline-svg :src="newQuestion.text.trim() ? 'assets/yes-icon.svg' : 'assets/magic-icon.svg'"
                    class="w-5 h-5 mr-1" :class="newQuestion.text.trim() ? 'text-primary' : 'text-white'" />
                  <span class="text-base font-medium">{{ newQuestion.text.trim() ? 'Add' : 'Suggest' }}</span>
                </button>
              </transition>
            </div>
          </div>
        </div>

        <!-- Posted Questions -->
        <div v-if="questions.length > 0" class="bg-neutral-100 rounded-[25px] p-7 mb-12">
          <transition-group name="list" tag="div" class="space-y-6">
            <div v-for="(question, index) in questions" :key="question.id" class="flex items-center justify-between">
              <div class="flex items-center space-x-4">
                <inline-svg
                  :src="question.response_type === 'scale' ? 'assets/scale-icon.svg' : 'assets/yes-no-icon.svg'"
                  :class="creatorAnswers[index] !== null ? 'text-primary' : 'text-neutral-400'" class="w-8 h-8" />
                <span
                  :class="['text-2xl font-bold', creatorAnswers[index] !== null ? 'text-primary' : 'text-neutral-400']">
                  {{ question.text }}
                </span>
                <inline-svg v-if="question.isAutogenerated" src="assets/magic-icon.svg" class="w-5 h-5 text-accent" />
              </div>
              <div v-if="question.response_type === 'scale'" class="flex space-x-3">
                <button v-for="n in 5" :key="n" @click="selectAnswer(index, n)" :class="['w-[30px] h-[30px] rounded-full border flex items-center justify-center',
                  n <= creatorAnswers[index] ? 'bg-primary border-primary' : 'bg-white border-neutral-300']"
                  :disabled="isSubmitted">
                  <div
                    :class="['w-[18px] h-[18px] rounded-full', n <= creatorAnswers[index] ? 'bg-white' : 'bg-transparent']">
                  </div>
                </button>
              </div>
              <div v-else class="flex space-x-3">
                <button @click="selectAnswer(index, true)"
                  :class="['w-[30px] h-[30px] rounded-full border flex items-center justify-center',
                    creatorAnswers[index] === true ? 'bg-primary border-primary' : 'bg-white border-neutral-300']" :disabled="isSubmitted">
                  <inline-svg src="assets/yes-icon.svg" :class="[
                    'w-4 h-4',
                    creatorAnswers[index] === true ? 'text-white' : 'text-neutral-300'
                  ]" />
                </button>
                <button @click="selectAnswer(index, false)"
                  :class="['w-[30px] h-[30px] rounded-full border flex items-center justify-center',
                    creatorAnswers[index] === false ? 'bg-primary border-primary' : 'bg-white border-neutral-300']" :disabled="isSubmitted">
                  <inline-svg src="assets/no-icon.svg" :class="[
                    'w-4 h-4',
                    creatorAnswers[index] === false ? 'text-white' : 'text-neutral-300'
                  ]" />
                </button>
              </div>
            </div>
          </transition-group>
        </div>

        <!-- New Publish Button Section with Dynamic Width Textboxes -->
        <div class="bg-accent-green rounded-[999px] p-4 flex items-center justify-between mb-4">
          <div class="flex items-center space-x-6">
            <!-- Survey Code Input -->
            <FancyInput
              v-model="surveyCode"
              :icon="'/assets/bookmark-icon.svg'"
              :placeholder="'survey-code'"
              :is-checking="isCheckingCode('survey')"
              :is-valid="isCodeValid('survey')"
              :is-error="isCodeInvalid('survey')"
              :loader-color="'#BE185D'"
              :valid-border-color="'border-neutral-300'"
              :neutral-border-color="'border-neutral-300'"
              :text-color="'text-neutral-500'"
              :error-bg-color="'bg-neutral'"
              :icon-color="'text-neutral-500'"
              @rotate="rotateCode('survey')"
              @input="handleCodeInput('survey')"
            />


            <!-- User Code Input @input="debounceCheckCode('user')" -->
            <FancyInput
              v-model="userCode"
              :icon="'/assets/user-icon.svg'"
              :placeholder="'user-name'"
              :is-checking="isCheckingCode('user')"
              :is-valid="isCodeValid('user')"
              :is-error="isCodeInvalid('user')"
              :loader-color="'#BE185D'"
              :valid-border-color="'border-neutral-300'"
              :neutral-border-color="'border-neutral-300'"
              :text-color="'text-neutral-500'"
              :icon-color="'text-neutral-500'"
              @rotate="rotateCode('user')"
              
              @input="handleCodeInput('survey')"
            />
          </div>
          <div>
            <button 
              @click="finishSurvey" 
              :disabled="!canPublish" 
              :class="[
                'w-[152px] h-14 rounded-full text-center text-2xl font-bold leading-9',
                !canPublish
                  ? 'bg-gray-400 text-gray-300 cursor-not-allowed'
                  : 'bg-primary text-white'
              ]"
            >
              Publish
            </button>
          </div>
        </div>

        <!-- Updated Error Notes Section -->
        <div class="mb-6">
          <div v-if="!allQuestionsAnswered || isCodeInvalid('survey') || isCodeInvalid('user')" class="flex flex-col space-y-2 text-accent">
            <div v-if="!allQuestionsAnswered" class="flex items-center space-x-2">
              <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
              <span class="text-sm font-medium">Complete self review before publishing</span>
            </div>
            <div v-if="isCodeInvalid('survey')" class="flex items-center space-x-2">
              <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
              <span class="text-sm font-medium">
                {{ getCodeErrorMessage('survey') }}
              </span>
            </div>
            <div v-if="isCodeInvalid('user')" class="flex items-center space-x-2">
              <inline-svg src="assets/info-icon.svg" class="text-accent w-5 h-5" />
              <span class="text-sm font-medium">
                {{ getCodeErrorMessage('user') }}
              </span>
            </div>
          </div>
        </div>
      </template>

      <!-- Published Section -->
      <div v-if="isPublished" class="bg-accent-green rounded-[25px] p-7 mb-12">
        <div class="w-full text-primary text-2xl font-bold font-['IBM Plex Sans'] leading-9 mb-6 text-left">
          The review is published and live!
        </div>

        <div class="flex items-center justify-start space-x-4 mb-4">
          <div class="flex items-center space-x-4">
            <span class="text-primary text-lg font-normal leading-7 whitespace-nowrap">Review code</span>
            <button
              class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary"
              @click="copyToClipboard(surveyCode)">
              <span class="text-base font-medium mr-2">{{ surveyCode }}</span>
              <inline-svg src="assets/copy-icon.svg" class="w-5 h-5 text-primary" />
            </button>
          </div>

          <div class="flex items-center space-x-4">
            <span class="text-primary text-lg font-normal leading-7 whitespace-nowrap">Review Link</span>
            <button
              class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary"
              @click="copyToClipboard(surveyLink)">
              <span class="text-base font-medium mr-2">Copy URL</span>
              <inline-svg src="assets/copy-icon.svg" class="w-5 h-5 text-primary" />
            </button>
          </div>
        </div>

        <div class="flex items-center justify-start space-x-4">
          <div class="flex items-center space-x-4">
            <span class="text-primary text-lg font-normal leading-7 whitespace-nowrap">User code</span>
            <button
              class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary"
              @click="copyToClipboard(userCode)">
              <span class="text-base font-medium mr-2">{{ userCode }}</span>
              <inline-svg src="assets/copy-icon.svg" class="w-5 h-5 text-primary" />
            </button>
          </div>

          <div class="flex items-center space-x-4">
            <span class="text-primary text-lg font-normal leading-7 whitespace-nowrap">Results Link</span>
            <button
              class="h-10 bg-white text-primary rounded-full flex items-center justify-between px-4 border border-primary"
              @click="copyToClipboard(resultsLink)">
              <span class="text-base font-medium mr-2">Copy URL</span>
              <inline-svg src="assets/copy-icon.svg" class="w-5 h-5 text-primary" />
            </button>
          </div>
        </div>
      </div>
    </div>
    <ToastView :message="toastMessage" :type="toastType" @hidden="clearToast" />
  </div>
</template> <!-- Is published section end -->

<script>
import { ref, computed, watch, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import api from '@/services/api';
import confetti from 'canvas-confetti';
import InlineSvg from 'vue-inline-svg';
import ToastView from '@/components/ToastView.vue';
import FancyInput from '@/components/FancyInput.vue';
import debounce from 'lodash/debounce';

export default {
  name: 'CreateView',
  components: {
    InlineSvg,
    ToastView,
    FancyInput,
  },
  setup() {
    const { t } = useI18n();
    const surveyTitle = ref(t('createView.title'));
    const surveyDescription = ref(t('createView.description'));
    const newQuestion = ref({ text: '', response_type: 'scale', isAutogenerated: false });
    const questions = ref([]);
    const creatorAnswers = ref([]);
    const isLoading = ref(false);
    const isSubmitted = ref(false);
    const isPublished = ref(false);
    const errorMessage = ref('');
    const showSuccess = ref(false);
    const surveyCode = ref('');
    const surveyLink = ref('');
    const inputFocused = ref(false);
    const toastMessage = ref('');
    const toastType = ref('');
    const userCode = ref('');
    const resultsLink = ref('');
    const availableCodes = ref({ survey: [], user: [] });
    const codeStatus = ref({ survey: null, user: null });
    const isChecking = ref({ survey: false, user: false });

    const isCheckingCode = (type) => isChecking.value[type];
    
    const isValidFormat = (code) => {
      const validFormat = /^[a-zA-Z0-9-]+$/;
      return typeof code === 'string' && code.length >= 5 && validFormat.test(code);
    };

    const handleCodeInput = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      if (isValidFormat(code)) {
        codeStatus.value[type] = null; // Reset status before checking
        debounceCheckCode(type);
      } else {
        codeStatus.value[type] = 'invalid';
        isChecking.value[type] = false;
      }
    };
    const getCodeErrorMessage = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      if (!code || code.length < 5) {
        return `${type === 'survey' ? 'Survey' : 'User'} code must be at least 5 characters long.`;
      }
      if (!/^[a-zA-Z0-9-]+$/.test(code)) {
        return `${type === 'survey' ? 'Survey' : 'User'} code can only contain letters, numbers, and hyphens.`;
      }
      return `Invalid ${type === 'survey' ? 'survey' : 'user'} code. Please choose a different one.`;
    };

    const canPublish = computed(() => 
      allQuestionsAnswered.value && 
      isCodeValid('survey') && 
      isCodeValid('user') && 
      !isLoading.value && 
      !isSubmitted.value
    );

    const debounceCheckCode = debounce((type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      if (isValidFormat(code)) {
        checkCodeAvailability(type);
      }
    }, 750);

    const isCodeValid = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      return isValidFormat(code) && codeStatus.value[type] === 'valid';
    };

    const isCodeInvalid = (type) => {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      return !isValidFormat(code) || codeStatus.value[type] === 'invalid';
    };

    const allQuestionsAnswered = computed(() =>
      questions.value.length > 0 &&
      creatorAnswers.value.length === questions.value.length &&
      creatorAnswers.value.every(answer => answer !== null && answer !== undefined)
    );

    const suggestedQuestions = [
      { text: "How well do I communicate my ideas?", response_type: "scale" },
      { text: "Am I open to feedback from others?", response_type: "boolean" },
      { text: "How effectively do I manage my time?", response_type: "scale" },
      { text: "Do I actively listen to you and other colleagues?", response_type: "boolean" },
      { text: "How well do I handle stress and pressure?", response_type: "scale" },
      { text: "Am I proactive in solving problems?", response_type: "boolean" },
      { text: "How would I rate my leadership skills?", response_type: "scale" },
      { text: "Do I consistently meet deadlines?", response_type: "boolean" },
      { text: "How adaptable am I to change?", response_type: "scale" },
      { text: "Do I take responsibility for my mistakes?", response_type: "boolean" }
    ];

    async function fetchInitialCodes() {
      try {
        const response = await api.getIds(10);
        availableCodes.value.survey = response.data.ids.slice(0, 5);
        availableCodes.value.user = response.data.ids.slice(5);
        surveyCode.value = availableCodes.value.survey[0];
        userCode.value = availableCodes.value.user[0];
      } catch (error) {
        console.error('Error fetching initial codes:', error);
        toastMessage.value = t('createView.errorFetchingCodes');
        toastType.value = 'error';
      }    
    }

    function rotateCode(type) {
      const codes = availableCodes.value[type];
      const currentCode = type === 'survey' ? surveyCode.value : userCode.value;
      const currentIndex = codes.indexOf(currentCode);
      const nextIndex = (currentIndex + 1) % codes.length;
      if (type === 'survey') {
        surveyCode.value = codes[nextIndex];
      } else {
        userCode.value = codes[nextIndex];
      }
    }

    async function checkCodeAvailability(type) {
      const code = type === 'survey' ? surveyCode.value : userCode.value;
      console.log(`Checking availability for ${type} code: ${code}`);

      isChecking.value[type] = true;
      codeStatus.value[type] = null;

      try {
        const response = await api.checkIdAvailability(code);
        console.log(`API response for ${type} code:`, response);

        // Ensure the animation runs for at least 1 second
        await new Promise(resolve => setTimeout(resolve, 1000));

        if (!response.data || typeof response.data.available !== 'boolean') {
          throw new Error('Unexpected API response format');
        }

        if (response.data.available) {
          codeStatus.value[type] = 'valid';
          console.log(`${type} code ${code} is available`);
          if (type === 'survey') {
            availableCodes.value.survey[0] = surveyCode.value;
          } else {
            availableCodes.value.user[0] = userCode.value;
          }
        } else {
          codeStatus.value[type] = 'invalid';
          console.log(`${type} code ${code} is not available`);
          toastMessage.value = t('createView.codeNotAvailable');
          toastType.value = 'error';
        }
      } catch (error) {
        console.error(`Error checking ${type} code availability:`, error);
        codeStatus.value[type] = 'invalid';
        toastMessage.value = t('createView.errorCheckingCode');
        toastType.value = 'error';
      } finally {
        isChecking.value[type] = false;
      }
    }

    function setQuestionType(type) {
      newQuestion.value.response_type = type;
      newQuestion.value.isAutogenerated = false;
    }

    function handleAddOrSuggest() {
      if (newQuestion.value.text.trim()) {
        addQuestion();
      } else {
        suggestQuestion();
      }
    }

    function addQuestion() {
      if (newQuestion.value.text.trim() && !isSubmitted.value) {
        questions.value.push({
          id: Date.now(),
          text: newQuestion.value.text,
          response_type: newQuestion.value.response_type,
          isAutogenerated: newQuestion.value.isAutogenerated
        });
        creatorAnswers.value.push(null);
        newQuestion.value = { text: '', response_type: 'scale', isAutogenerated: false };
      }
    }

    function suggestQuestion() {
      const randomIndex = Math.floor(Math.random() * suggestedQuestions.length);
      const suggestedQuestion = suggestedQuestions[randomIndex];

      newQuestion.value = {
        text: suggestedQuestion.text,
        response_type: suggestedQuestion.response_type,
        isAutogenerated: true
      };
    }

    function handleQuestionChange() {
      if (newQuestion.value.isAutogenerated && newQuestion.value.text !== suggestedQuestions.find(q => q.text === newQuestion.value.text)?.text) {
        newQuestion.value.isAutogenerated = false;
      }
    }

    function suggestReplacementQuestion() {
      suggestQuestion();
    }

    function selectAnswer(index, value) {
      if (!isSubmitted.value) {
        creatorAnswers.value[index] = value;
      }
    }

    function celebrateSuccess() {
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 }
      });
    }

    function clearToast() {
      toastMessage.value = '';
      toastType.value = '';
    }

    async function finishSurvey() {
      if (isSubmitted.value || !allQuestionsAnswered.value) return;

      isLoading.value = true;
      errorMessage.value = '';
      try {
        const surveyData = {
          survey_id: surveyCode.value,
          user_code: userCode.value,
          title: surveyTitle.value,
          description: surveyDescription.value,
          questions: questions.value.map((q, index) => ({
            ...q,
            creator_answer: creatorAnswers.value[index]
          }))
        };

        const response = await api.createSurvey(surveyData);
        console.log('Survey created', response.data);
        surveyLink.value = response.data.share_link;
        resultsLink.value = `/results/${surveyCode.value}/${userCode.value}`;
        isSubmitted.value = true;
        isPublished.value = true;
        showSuccess.value = true;
        celebrateSuccess();
        toastMessage.value = t('createView.toastSuccess');
        toastType.value = 'success';
      } catch (error) {
        console.error('Error creating survey:', error);
        errorMessage.value = t('createView.toastError');
        toastMessage.value = t('createView.toastError');
        toastType.value = 'error';
      } finally {
        isLoading.value = false;
      }
    }

    onMounted(async () => {
      await fetchInitialCodes();
    });

    watch(() => newQuestion.value.text, handleQuestionChange);

    function copyToClipboard(text) {
      navigator.clipboard.writeText(text).then(() => {
        toastMessage.value = t('createView.copySuccess');
        toastType.value = 'success';
      }, (err) => {
        console.error('Could not copy text: ', err);
        toastMessage.value = t('createView.copyError');
        toastType.value = 'error';
      });
    }

    return {
      t,
      surveyTitle,
      surveyDescription,
      newQuestion,
      questions,
      creatorAnswers,
      isLoading,
      isSubmitted,
      isPublished,
      errorMessage,
      showSuccess,
      surveyCode,
      surveyLink,
      allQuestionsAnswered,
      inputFocused,
      toastMessage,
      toastType,
      setQuestionType,
      suggestReplacementQuestion,
      suggestQuestion,
      addQuestion,
      handleAddOrSuggest,
      selectAnswer,
      finishSurvey,
      clearToast,
      userCode,
      resultsLink,
      rotateCode,
      checkCodeAvailability,
      copyToClipboard,
      isCheckingCode,
      isCodeValid,
      isCodeInvalid,
      debounceCheckCode,
      canPublish,
      isValidFormat,
      handleCodeInput,
      getCodeErrorMessage,
    };
  }
}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&display=swap');

/* Animations */
@keyframes blink {
  0%, 100% { opacity: 0; }
  50% { opacity: 1; }
}


/* General styles */
.animate-blink {
  animation: blink 1s infinite;
}

/* Fancy border styles */
/* Updated Fancy border styles */
.fancy-border {
  position: relative;
  border-radius: 9999px;
  overflow: hidden;
}

.fancy-border {
  --offset: 3px;
  background: white;  /* Changed from the tutorial's dark background */
  border-radius: 9999px;
  position: relative;
  overflow: hidden;
  height: 40px;  /* Adjust as needed */
  width: 100%;  /* Adjust as needed */
}

.fancy-border::before {
  content: '';
  background: conic-gradient(transparent 270deg, red, transparent);
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  aspect-ratio: 1;
  width: 100%;
  opacity: 0;
  transition: opacity 0.3s ease;
}

.fancy-border.checking::before {
  opacity: 1;
  animation: rotate 2s linear infinite;
}

.fancy-border::after {
  content: '';
  background: inherit;
  border-radius: inherit;
  position: absolute;
  inset: var(--offset);
}

.fancy-border > div {
  position: relative;
  z-index: 10;
  height: 100%;
}

@keyframes rotate {
  from {
    transform: translate(-50%, -50%) scale(1.4) rotate(0turn);
  }
  to {
    transform: translate(-50%, -50%) scale(1.4) rotate(1turn);
  }
}



/* Code input styles */
.code-input-container {
  position: relative;
}

.code-input-container .measure-span {
  visibility: hidden;
  white-space: pre;
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
}

/* Transition styles */
.fade-scale-enter-active,
.fade-scale-leave-active,
.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}

.fade-scale-enter-from,
.fade-scale-leave-to {
  opacity: 0;
  transform: scale(0.9);
}

.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}

.list-move {
  transition: transform 0.5s ease;
}
</style>